version: 0.1

environment_variables:
  plaintext:
    PACKER_NO_COLOR: "1"

phases:
  install:
    commands:
      - apt-get update || echo "Failed to run apt-get update."
      - apt-get install jq -y || echo "Failed to install and/or update jq."
      - wget https://releases.hashicorp.com/packer/1.0.0/packer_1.0.0_linux_amd64.zip
      - unzip packer_1.0.0_linux_amd64.zip
  pre_build:
    commands:
      - curl -qL 169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > credentials.json
      - mkdir -p ~/.aws
      - echo "[default]" > ~/.aws/credentials
      - echo "aws_access_key_id = $(cat credentials.json | jq '.AccessKeyId' | sed s'/"//g')" >> ~/.aws/credentials
      - echo "aws_secret_access_key = $(cat credentials.json | jq '.SecretAccessKey' | sed s'/"//g')" >> ~/.aws/credentials
      - echo "aws_session_token = $(cat credentials.json | jq '.Token' | sed s'/"//g')" >> ~/.aws/credentials
  build:
    commands:
#      - ./packer build -var "aws_region=ap-southeast-2" "deploy/packer.json"
      - ./packer build -var "aws_region=ap-southeast-2" "deploy/packerwindows.json"
